### PR TITLE
fix: use rfkill when toggling bluetooth

### LINKED ISSUE #1498: Settings can't turn Bluetooth on if it was last turned off by the applet
cosmic-settings: 086f501
cosmic-applets: ae4a2a7

If I turn off Bluetooth in the applet, then turning it back on in Settings doesn't work (no devices are ever shown). I have to turn it back on in the applet (then sometimes also toggle it again in Settings) before it will work again.

https://github.com/user-attachments/assets/ea75cb32-3dd8-4dca-afde-21b9cd6d8b7e

If I just turn it off from Settings, then I can turn it back on in Settings and it works.

### PR DESCRIPTION
**Pull request by wash2**
fixes #1498 & #1318

### CODE REVIEW

**Review by garrettjwilke — DISMISSED** [review]

**Review by mmstick — DISMISSED** [review]

File: subscriptions/bluetooth/src/device.rs [hunk 1]
```diff
@@ -255,6 +255,8 @@ pub async fn connect_device(connection: zbus::Connection, device_path: OwnedObje
         }
     }
 
+    dbg!("failed to connect after retries");
+    dbg!("failed to connect after retries");
```
Comment (jacobgkau) [inline subscriptions/bluetooth/src/device.rs]: Are there supposed to be two of these log lines?

**Review by mmstick — APPROVED** [review]
